<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Authors>Misaki</Authors>
    <AssemblyVersion>1.3.7</AssemblyVersion>
    <Version>$(AssemblyVersion)</Version>
    <PackageProjectUrl>https://git.personalnas.com/Misaki/Misaki.HighPerformance.git</PackageProjectUrl>
    <RepositoryUrl>https://git.personalnas.com/Misaki/Misaki.HighPerformance.git</RepositoryUrl>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <ContentTargetFolders>contentFiles</ContentTargetFolders>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <IsAotCompatible>True</IsAotCompatible>
    <DefineConstants>$(DefineConstants);ENABLE_COLLECTION_CHECKS</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <IsAotCompatible>True</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Misaki.HighPerformance\Misaki.HighPerformance.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="contentFiles\cs\any\**\*.cs">
      <Pack>true</Pack>
      <PackagePath>contentFiles\cs\any\</PackagePath>
      <BuildAction>Compile</BuildAction>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <None Update="contentFiles\cs\any\Collections\FixedString.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>FixedString.gen.cs</LastGenOutput>
    </None>
    <None Update="contentFiles\cs\any\Collections\FixedText.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>FixedText.gen.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="contentFiles\cs\any\Collections\FixedString.gen.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>FixedString.tt</DependentUpon>
    </Compile>
    <Compile Update="contentFiles\cs\any\Collections\FixedText.gen.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>FixedText.tt</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
